name: Package Chrome Extension

on:
  push:
    branches:
      - main

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Package extension
        run: zip -r chrome-extension.zip ./frontend
